server:
  port: 8092
spring:
  application:
    name: gateway

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    preferIpAddress: true

zuul:
  ignoredServices: '*'
  routes:
    microservice1:
      path: /api/microservice1/**
      serviceId: microservice1
    microservice2:
      path: /api/microservice2/**
      serviceId: microservice2