server:
  port: 8092
spring:
  application:
    name: gateway
  data:
    mongodb:
      database: psinder
      host: localhost
      port: 27017

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    preferIpAddress: true

zuul:
  ignoredServices: '*'
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
    cards-service:
      path: /cards-service/**
      serviceId: cards-service
    chats-service:
      path: /chats-service/**
      serviceId: chats-service
    maps-service:
      path: /maps-service/**
      serviceId: maps-service
    users-service:
      path: /users-service/**
      serviceId: users-service
    payments-service:
      path: /payments-service/**
      serviceId: payments-service

pl:
  psinder:
    jwtExpirationMs: 86400000
    jwtSecret: LejeToDoFantyNieColiNicMnieNieBoliBoLejeDoWoliSypieJejKoksANieSoliSypieJejMollyNieKoliLejeToDoFantyNieColiCzasMnieGoni
